# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 606c3d074e069c09292dcc1562169773d9c16291a92c4f5aa3cd65086a26fa0ac8e2a238d138420564de9af795bd806cbfcd0f17a3337666c59f5964c99d701b

test:
  secret_key_base: f7dd35f15fc890e3c6742b185088d107a86cd81628ba9c9d255c851d33e394576bdc66408f1e65d93ede3cf6d9d37302d885cc87f5c98f6695c8990e9a7e5b8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
